# CATALOGUE_HOST: catalogue.rachelsigao.online
# USER_HOST: user.rachelsigao.online
# CART_HOST: cart.rachelsigao.online
# SHIPPING_HOST: shipping.rachelsigao.online
# PAYMENT_HOST: payment.rachelsigao.online

# for terraform-roboshop-module
CATALOGUE_HOST: catalogue.backend-{{ env }}.rachelsigao.online
USER_HOST: user.backend-{{ env }}.rachelsigao.online
CART_HOST: cart.backend-{{ env }}.rachelsigao.online
SHIPPING_HOST: shipping.backend-{{ env }}.rachelsigao.online
PAYMENT_HOST: payment.backend-{{ env }}.rachelsigao.online