CATALOGUE_HOST: catalogue.rachelsigao.online
USER_HOST: user.rachelsigao.online
CART_HOST: cart.rachelsigao.online
SHIPPING_HOST: shipping.rachelsigao.online
PAYMENT_HOST: payment.rachelsigao.online

# for terraform-roboshop-module
# CATALOGUE_HOST: catalogue-{{ env }}.rachelsigao.online
# USER_HOST: user-{{ env }}.rachelsigao.online
# CART_HOST: cart-{{ env }}.rachelsigao.online    
# SHIPPING_HOST: shipping-{{ env }}.rachelsigao.online
# PAYMENT_HOST: payment-{{ env }}.rachelsigao.online